FROM python:3.7.3

RUN mkdir -p /manager
RUN mkdir -p /logs
RUN mkdir -p /simulation-tools

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY sub_modules.py /sub_modules.py
COPY manager/ /manager/
COPY simulation-tools/ /simulation-tools/

WORKDIR /

CMD [ "python3", "-u", "-m", "manager.manager" ]
