FROM python:3.7.3

RUN mkdir -p /manager
RUN mkdir -p /tools

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY manager/ /manager/
COPY tools/ /tools/

WORKDIR /

CMD [ "python3", "-u", "-m", "manager.manager" ]
