FROM python:3.7.3

RUN mkdir -p /dummy
RUN mkdir -p /tools
RUN mkdir -p /logs

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY dummy/ /dummy/
COPY tools/ /tools/

WORKDIR /

CMD [ "python3", "-u", "-m", "dummy.dummy" ]
