FROM python:3.7.3

RUN mkdir -p /tests/dummy
RUN mkdir -p /tests/listener
RUN mkdir -p /tests/manager
RUN mkdir -p /tests/omega
RUN mkdir -p /tests/tools

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY tools/ /tests/tools/
COPY dummy/ /tests/dummy/
COPY listener/ tests/listener/
COPY manager/ /tests/manager/

WORKDIR /tests

CMD [ "python3", "-u", "-m", "unittest", "discover", "-s", ".", "-p", "*.py" ]
