FROM python:3.7.3

RUN mkdir -p /omega
RUN mkdir -p /tools

COPY requirements.txt /requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /requirements.txt

COPY omega/ /omega/
COPY tools/ /tools/

WORKDIR /

CMD [ "python3", "-u", "-m", "omega.omega" ]
